// GENERATED by tools/gen_parity_fixtures.py — do not hand-edit.
const FIXTURES = [
  {
    "name": "round_to_increment(101.2, 2.5, down=False)",
    "fn": "roundToIncrement",
    "args": [
      101.2,
      2.5,
      false
    ],
    "expected": 100.0,
    "kind": "scalar"
  },
  {
    "name": "round_to_increment(103.0, 2.5, down=False)",
    "fn": "roundToIncrement",
    "args": [
      103.0,
      2.5,
      false
    ],
    "expected": 102.5,
    "kind": "scalar"
  },
  {
    "name": "round_to_increment(99.0, 2.5, down=True)",
    "fn": "roundToIncrement",
    "args": [
      99.0,
      2.5,
      true
    ],
    "expected": 97.5,
    "kind": "scalar"
  },
  {
    "name": "round_to_increment(105.0, 10.0, down=False)",
    "fn": "roundToIncrement",
    "args": [
      105.0,
      10.0,
      false
    ],
    "expected": 100.0,
    "kind": "scalar"
  },
  {
    "name": "round_to_increment(135.0, 10.0, down=False)",
    "fn": "roundToIncrement",
    "args": [
      135.0,
      10.0,
      false
    ],
    "expected": 140.0,
    "kind": "scalar"
  },
  {
    "name": "rir_ramp(1)",
    "fn": "rirRamp",
    "args": [
      1
    ],
    "expected": [
      0
    ],
    "kind": "scalar"
  },
  {
    "name": "rir_ramp(2)",
    "fn": "rirRamp",
    "args": [
      2
    ],
    "expected": [
      1,
      0
    ],
    "kind": "scalar"
  },
  {
    "name": "rir_ramp(3)",
    "fn": "rirRamp",
    "args": [
      3
    ],
    "expected": [
      2,
      1,
      0
    ],
    "kind": "scalar"
  },
  {
    "name": "rir_ramp(4)",
    "fn": "rirRamp",
    "args": [
      4
    ],
    "expected": [
      2,
      1,
      1,
      0
    ],
    "kind": "scalar"
  },
  {
    "name": "next_in_rotation(None)",
    "fn": "nextInRotation",
    "args": [
      null
    ],
    "expected": "push",
    "kind": "scalar"
  },
  {
    "name": "next_in_rotation('push')",
    "fn": "nextInRotation",
    "args": [
      "push"
    ],
    "expected": "pull",
    "kind": "scalar"
  },
  {
    "name": "next_in_rotation('rest')",
    "fn": "nextInRotation",
    "args": [
      "rest"
    ],
    "expected": "push",
    "kind": "scalar"
  },
  {
    "name": "floor: safe exercise never capped",
    "fn": "rirFloor",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "has_rack_safeties": false,
        "has_smith_machine": false,
        "dumbbell_max": null
      },
      false
    ],
    "expected": [
      0,
      "none"
    ],
    "kind": "rirFloor"
  },
  {
    "name": "floor: barbell alone, no safeties",
    "fn": "rirFloor",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "has_rack_safeties": false,
        "has_smith_machine": false,
        "dumbbell_max": null
      },
      false
    ],
    "expected": [
      1,
      "solo_no_safeties"
    ],
    "kind": "rirFloor"
  },
  {
    "name": "floor: rack safeties remove cap",
    "fn": "rirFloor",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "has_rack_safeties": true,
        "has_smith_machine": false,
        "dumbbell_max": null
      },
      false
    ],
    "expected": [
      0,
      "none"
    ],
    "kind": "rirFloor"
  },
  {
    "name": "floor: spotter removes cap",
    "fn": "rirFloor",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "has_rack_safeties": false,
        "has_smith_machine": false,
        "dumbbell_max": null
      },
      true
    ],
    "expected": [
      0,
      "none"
    ],
    "kind": "rirFloor"
  },
  {
    "name": "prescribe: cap only binds on last set",
    "fn": "prescribe",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "barbell_bench_press",
        "current_weight": 100.0,
        "current_rep_target": 5,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      3,
      {
        "has_rack_safeties": false,
        "has_smith_machine": false,
        "dumbbell_max": null
      },
      false,
      "2026-08-15"
    ],
    "expected": [
      {
        "set_index": 1,
        "target_weight": 100.0,
        "target_reps": 5,
        "target_rir": 2,
        "capped": false,
        "cap_reason": "none",
        "rest_seconds": 120
      },
      {
        "set_index": 2,
        "target_weight": 100.0,
        "target_reps": 5,
        "target_rir": 1,
        "capped": false,
        "cap_reason": "none",
        "rest_seconds": 120
      },
      {
        "set_index": 3,
        "target_weight": 100.0,
        "target_reps": 5,
        "target_rir": 1,
        "capped": true,
        "cap_reason": "solo_no_safeties",
        "rest_seconds": 120
      }
    ],
    "kind": "prescriptions"
  },
  {
    "name": "classify: set1 miss",
    "fn": "classify",
    "args": [
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 9,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 10,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 10,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ]
    ],
    "expected": "miss",
    "kind": "scalar"
  },
  {
    "name": "classify: later-set miss = partial",
    "fn": "classify",
    "args": [
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 10,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 10,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 8,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ]
    ],
    "expected": "partial",
    "kind": "scalar"
  },
  {
    "name": "classify: clean hit",
    "fn": "classify",
    "args": [
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 10,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 10,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 10,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ]
    ],
    "expected": "hit",
    "kind": "scalar"
  },
  {
    "name": "progress: clean hit adds a rep",
    "fn": "progress",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 10,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 10,
          "rir": 2,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 10,
          "rir": 1,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 10,
          "rir": 1,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "progress_reps",
      "next_weight": 60.0,
      "next_rep_target": 11,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: top of range adds load, resets reps",
    "fn": "progress",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 15,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 15,
          "rir": 2,
          "target_weight": 60.0,
          "target_reps": 15,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 15,
          "rir": 1,
          "target_weight": 60.0,
          "target_reps": 15,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 15,
          "rir": 1,
          "target_weight": 60.0,
          "target_reps": 15,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "progress_load",
      "next_weight": 65.0,
      "next_rep_target": 10,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: high RIR moves by reps not load",
    "fn": "progress",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 10,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 10,
          "rir": 5,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 10,
          "rir": 4,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 10,
          "rir": 4,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "progress_reps",
      "next_weight": 60.0,
      "next_rep_target": 12,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: failure on set1 holds",
    "fn": "progress",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 10,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 10,
          "rir": 0,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 10,
          "rir": 0,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 10,
          "rir": 0,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "hold_consolidate",
      "next_weight": 60.0,
      "next_rep_target": 10,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: missing RIR treated as neutral",
    "fn": "progress",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 10,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 10,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 10,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 10,
          "rir": null,
          "target_weight": 60.0,
          "target_reps": 10,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "progress_reps",
      "next_weight": 60.0,
      "next_rep_target": 11,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: capped RIR1 on set1 progresses",
    "fn": "progress",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "barbell_bench_press",
        "current_weight": 100.0,
        "current_rep_target": 5,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 100.0,
          "reps": 5,
          "rir": 2,
          "target_weight": 100.0,
          "target_reps": 5,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 100.0,
          "reps": 5,
          "rir": 1,
          "target_weight": 100.0,
          "target_reps": 5,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 100.0,
          "reps": 5,
          "rir": 1,
          "target_weight": 100.0,
          "target_reps": 5,
          "target_rir": 1,
          "stopped_at_cap": true,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "progress_reps",
      "next_weight": 100.0,
      "next_rep_target": 6,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: capped set1 not misread as true failure (bug guard)",
    "fn": "progress",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "barbell_bench_press",
        "current_weight": 100.0,
        "current_rep_target": 5,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 100.0,
          "reps": 5,
          "rir": 1,
          "target_weight": 100.0,
          "target_reps": 5,
          "target_rir": 2,
          "stopped_at_cap": true,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 100.0,
          "reps": 5,
          "rir": 1,
          "target_weight": 100.0,
          "target_reps": 5,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 100.0,
          "reps": 5,
          "rir": 1,
          "target_weight": 100.0,
          "target_reps": 5,
          "target_rir": 1,
          "stopped_at_cap": true,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "progress_reps",
      "next_weight": 100.0,
      "next_rep_target": 6,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: later-set shortfall = fatigue not overload",
    "fn": "progress",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 12,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 12,
          "rir": 2,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 11,
          "rir": 1,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 8,
          "rir": 0,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "repeat_fatigue",
      "next_weight": 60.0,
      "next_rep_target": 12,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 1
    },
    "kind": "decision"
  },
  {
    "name": "progress: steep dropoff flagged (note count)",
    "fn": "progress",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 12,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 12,
          "rir": 2,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 6,
          "rir": 1,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 4,
          "rir": 0,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "repeat_fatigue",
      "next_weight": 60.0,
      "next_rep_target": 12,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 1
    },
    "kind": "decision",
    "notes_min": 1
  },
  {
    "name": "progress: fatigue patience boundary falls through",
    "fn": "progress",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 12,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 2,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 12,
          "rir": 2,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 11,
          "rir": 1,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 8,
          "rir": 0,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "progress_reps",
      "next_weight": 60.0,
      "next_rep_target": 13,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: 3rd consecutive miss triggers stall intervention",
    "fn": "progress",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 12,
        "consecutive_stalls": 2,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 9,
          "rir": 0,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 9,
          "rir": 0,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 8,
          "rir": 0,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "stall_intervention",
      "next_weight": 60.0,
      "next_rep_target": 12,
      "consecutive_stalls": 3,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: a hit resets the stall counter",
    "fn": "progress",
    "args": [
      {
        "id": "lat_pulldown",
        "name": "Lat Pulldown",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps",
          "upper back"
        ],
        "rep_range": [
          10,
          15
        ],
        "load_increment": 5.0,
        "equipment": "machine",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 12,
        "consecutive_stalls": 2,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 60.0,
          "reps": 12,
          "rir": 2,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 60.0,
          "reps": 12,
          "rir": 1,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 60.0,
          "reps": 12,
          "rir": 1,
          "target_weight": 60.0,
          "target_reps": 12,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "progress_reps",
      "next_weight": 60.0,
      "next_rep_target": 13,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: off-grid load adds full increment (bug guard)",
    "fn": "progress",
    "args": [
      {
        "id": "smith",
        "name": "Smith Bench",
        "primary_muscles": [
          "chest"
        ],
        "secondary_muscles": [],
        "rep_range": [
          6,
          10
        ],
        "load_increment": 10.0,
        "equipment": "barbell",
        "failure_risk": "bailout_possible",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "smith",
        "current_weight": 135.0,
        "current_rep_target": 10,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 135.0,
          "reps": 10,
          "rir": 2,
          "target_weight": 135.0,
          "target_reps": 10,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 135.0,
          "reps": 10,
          "rir": 1,
          "target_weight": 135.0,
          "target_reps": 10,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 135.0,
          "reps": 10,
          "rir": 1,
          "target_weight": 135.0,
          "target_reps": 10,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "progress_load",
      "next_weight": 145.0,
      "next_rep_target": 6,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "progress: bodyweight never adds load",
    "fn": "progress",
    "args": [
      {
        "id": "pullup",
        "name": "Pull-Up",
        "primary_muscles": [
          "lats"
        ],
        "secondary_muscles": [
          "biceps"
        ],
        "rep_range": [
          5,
          10
        ],
        "load_increment": 2.5,
        "equipment": "bodyweight",
        "failure_risk": "safe_to_failure",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": true
      },
      {
        "exercise_id": "pullup",
        "current_weight": 0.0,
        "current_rep_target": 10,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      [
        {
          "set_index": 1,
          "weight": 0.0,
          "reps": 10,
          "rir": 2,
          "target_weight": 0.0,
          "target_reps": 10,
          "target_rir": 2,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 2,
          "weight": 0.0,
          "reps": 10,
          "rir": 1,
          "target_weight": 0.0,
          "target_reps": 10,
          "target_rir": 1,
          "stopped_at_cap": false,
          "is_warmup": false
        },
        {
          "set_index": 3,
          "weight": 0.0,
          "reps": 10,
          "rir": 1,
          "target_weight": 0.0,
          "target_reps": 10,
          "target_rir": 0,
          "stopped_at_cap": false,
          "is_warmup": false
        }
      ],
      "2026-08-15"
    ],
    "expected": {
      "diagnosis": "progress_reps",
      "next_weight": 0.0,
      "next_rep_target": 11,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0
    },
    "kind": "decision"
  },
  {
    "name": "prescribe: layoff >14d reduces weight",
    "fn": "prescribe",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "barbell_bench_press",
        "current_weight": 100.0,
        "current_rep_target": 5,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-07-16",
        "observed_dropoff": null
      },
      3,
      {
        "has_rack_safeties": true,
        "has_smith_machine": false,
        "dumbbell_max": null
      },
      false,
      "2026-08-15"
    ],
    "expected": 90.0,
    "kind": "firstPrescriptionWeight"
  },
  {
    "name": "prescribe: short gap does not reduce weight",
    "fn": "prescribe",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "barbell_bench_press",
        "current_weight": 100.0,
        "current_rep_target": 5,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-11",
        "observed_dropoff": null
      },
      3,
      {
        "has_rack_safeties": true,
        "has_smith_machine": false,
        "dumbbell_max": null
      },
      false,
      "2026-08-15"
    ],
    "expected": 100.0,
    "kind": "firstPrescriptionWeight"
  },
  {
    "name": "prescribe: layoff deload keeps off-grid weight loadable",
    "fn": "prescribe",
    "args": [
      {
        "id": "smith",
        "name": "Smith Bench",
        "primary_muscles": [
          "chest"
        ],
        "secondary_muscles": [],
        "rep_range": [
          6,
          10
        ],
        "load_increment": 10.0,
        "equipment": "barbell",
        "failure_risk": "bailout_possible",
        "substitutes": [],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "exercise_id": "smith",
        "current_weight": 135.0,
        "current_rep_target": 6,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-07-16",
        "observed_dropoff": null
      },
      3,
      {
        "has_rack_safeties": true,
        "has_smith_machine": false,
        "dumbbell_max": null
      },
      false,
      "2026-08-15"
    ],
    "expected": 125.0,
    "kind": "firstPrescriptionWeight"
  },
  {
    "name": "apply: folds decision into state",
    "fn": "apply",
    "args": [
      {
        "exercise_id": "lat_pulldown",
        "current_weight": 60.0,
        "current_rep_target": 10,
        "consecutive_stalls": 0,
        "consecutive_fatigue": 0,
        "last_performed_date": "2026-08-15",
        "observed_dropoff": null
      },
      {
        "diagnosis": "progress_reps",
        "next_weight": 60.0,
        "next_rep_target": 11,
        "consecutive_stalls": 0,
        "message": "Next time: 60.0 \u00d7 11.",
        "consecutive_fatigue": 0,
        "notes": [],
        "intervention_options": []
      },
      "2026-08-15"
    ],
    "expected": {
      "exercise_id": "lat_pulldown",
      "current_weight": 60.0,
      "current_rep_target": 11,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0,
      "last_performed_date": "2026-08-15",
      "observed_dropoff": null
    },
    "kind": "state"
  },
  {
    "name": "bootstrap: first log becomes state",
    "fn": "bootstrap",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "set_index": 1,
        "weight": 95.0,
        "reps": 6,
        "rir": null,
        "target_weight": 0,
        "target_reps": 0,
        "target_rir": 0,
        "stopped_at_cap": false,
        "is_warmup": false
      },
      "2026-08-15"
    ],
    "expected": {
      "exercise_id": "barbell_bench_press",
      "current_weight": 95.0,
      "current_rep_target": 6,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0,
      "last_performed_date": "2026-08-15",
      "observed_dropoff": null
    },
    "kind": "state"
  },
  {
    "name": "bootstrap: clamps reps to range top",
    "fn": "bootstrap",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "set_index": 1,
        "weight": 95.0,
        "reps": 20,
        "rir": null,
        "target_weight": 0,
        "target_reps": 0,
        "target_rir": 0,
        "stopped_at_cap": false,
        "is_warmup": false
      },
      "2026-08-15"
    ],
    "expected": {
      "exercise_id": "barbell_bench_press",
      "current_weight": 95.0,
      "current_rep_target": 8,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0,
      "last_performed_date": "2026-08-15",
      "observed_dropoff": null
    },
    "kind": "state"
  },
  {
    "name": "bootstrap: clamps reps to range floor",
    "fn": "bootstrap",
    "args": [
      {
        "id": "barbell_bench_press",
        "name": "Barbell Bench Press",
        "primary_muscles": [
          "chest",
          "front delts"
        ],
        "secondary_muscles": [
          "triceps"
        ],
        "rep_range": [
          5,
          8
        ],
        "load_increment": 2.5,
        "equipment": "barbell",
        "failure_risk": "needs_safeties",
        "substitutes": [
          "Dumbbell Press",
          "Machine Chest Press"
        ],
        "default_rest_seconds": 120,
        "is_bodyweight": false
      },
      {
        "set_index": 1,
        "weight": 95.0,
        "reps": 1,
        "rir": null,
        "target_weight": 0,
        "target_reps": 0,
        "target_rir": 0,
        "stopped_at_cap": false,
        "is_warmup": false
      },
      "2026-08-15"
    ],
    "expected": {
      "exercise_id": "barbell_bench_press",
      "current_weight": 95.0,
      "current_rep_target": 5,
      "consecutive_stalls": 0,
      "consecutive_fatigue": 0,
      "last_performed_date": "2026-08-15",
      "observed_dropoff": null
    },
    "kind": "state"
  },
  {
    "name": "weekly_volume: secondaries at half",
    "fn": "weeklyVolume",
    "args": [
      [
        [
          {
            "id": "p",
            "name": "Press",
            "primary_muscles": [
              "chest"
            ],
            "secondary_muscles": [
              "triceps"
            ],
            "rep_range": [
              8,
              12
            ],
            "load_increment": 10.0,
            "equipment": "barbell",
            "failure_risk": "safe_to_failure",
            "substitutes": [],
            "default_rest_seconds": 120,
            "is_bodyweight": false
          },
          4
        ]
      ]
    ],
    "expected": {
      "chest": 4.0,
      "triceps": 2.0
    },
    "kind": "volume"
  },
  {
    "name": "rotation_volume: sums across days",
    "fn": "rotationVolume",
    "args": [
      {
        "push": [
          [
            {
              "id": "p",
              "name": "Press",
              "primary_muscles": [
                "chest"
              ],
              "secondary_muscles": [
                "triceps"
              ],
              "rep_range": [
                8,
                12
              ],
              "load_increment": 10.0,
              "equipment": "barbell",
              "failure_risk": "safe_to_failure",
              "substitutes": [],
              "default_rest_seconds": 120,
              "is_bodyweight": false
            },
            3
          ]
        ],
        "pull": [
          [
            {
              "id": "lat_pulldown",
              "name": "Lat Pulldown",
              "primary_muscles": [
                "lats"
              ],
              "secondary_muscles": [
                "biceps",
                "upper back"
              ],
              "rep_range": [
                10,
                15
              ],
              "load_increment": 5.0,
              "equipment": "machine",
              "failure_risk": "safe_to_failure",
              "substitutes": [],
              "default_rest_seconds": 120,
              "is_bodyweight": false
            },
            2
          ]
        ]
      }
    ],
    "expected": {
      "chest": 3.0,
      "lats": 2.0,
      "triceps": 1.5,
      "biceps": 1.0,
      "upper back": 1.0
    },
    "kind": "volume"
  },
  {
    "name": "rotation_volume: rejects unknown day",
    "fn": "rotationVolume",
    "args": [
      {
        "cardio": [
          [
            {
              "id": "p",
              "name": "Press",
              "primary_muscles": [
                "chest"
              ],
              "secondary_muscles": [
                "triceps"
              ],
              "rep_range": [
                8,
                12
              ],
              "load_increment": 10.0,
              "equipment": "barbell",
              "failure_risk": "safe_to_failure",
              "substitutes": [],
              "default_rest_seconds": 120,
              "is_bodyweight": false
            },
            3
          ]
        ]
      }
    ],
    "expected": null,
    "kind": "throws"
  },
  {
    "name": "routine_preview: full rotation, default 3 sets",
    "fn": "routinePreview",
    "args": [
      3
    ],
    "expected": {
      "triceps": 10.5,
      "front delts": 9.0,
      "biceps": 7.5,
      "upper back": 7.5,
      "chest": 6.0,
      "lats": 6.0,
      "quads": 6.0,
      "hamstrings": 3.0,
      "calves": 3.0,
      "side delts": 1.5,
      "glutes": 1.5
    },
    "kind": "volume"
  }
];
